version: "3.9"

services:
    # Proxy
    traefik:
        image: "traefik:v2.9"
        container_name: "traefik"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    # Puller
    timescale:
        image: timescale/timescaledb:latest-pg12
        restart: always
        volumes:
            - ./timescale:/var/lib/postgresql/data
        ports:
            - "5500:5432"
        environment:
            POSTGRES_PASSWORD: password1234

    finhub-puller:
        image: finhub-puller:latest
        volumes:
            - ./finhub_puller:/finhub_puller
        ports:
            - "8000:8000"
        stop_grace_period: 60s
        restart: always
        labels:
            - "traefik.enable=true"
            # The domain the service will respond to
            - "traefik.http.routers.puller.rule=Host(`puller.localhost`)"
            # Allow request only from the predefined entry point named "web"
            - "traefik.http.routers.puller.entrypoints=web"

    # Wallet admin
    mongo-db:
        image: mongo:4.4.17-rc2
        restart: always
        volumes:
            - ./mongo:/data

    wallet-admin:
        image: wallet-admin:latest
        volumes:
            - ./wallet_admin:/wallet_admin
        restart: always
        ports:
            - "3010:3010"
        labels:
            - "traefik.enable=true"
            # The domain the service will respond to
            - "traefik.http.routers.walletadmin.rule=Host(`walletadmin.localhost`)"
            # Allow request only from the predefined entry point named "web"
            - "traefik.http.routers.walletadmin.entrypoints=web"

    wallet-front:
        image: frontend:latest
        volumes:
            - ./frontend:/frontend
        restart: always
        ports:
            - "3000:3000"
        labels:
            - "traefik.enable=true"
            # The domain the service will respond to
            - "traefik.http.routers.wallet.rule=Host(`wallet.localhost`)"
            # Allow request only from the predefined entry point named "web"
            - "traefik.http.routers.wallet.entrypoints=web"
