version: "3.7"

services:
    django:
        image: stocklooker
        volumes:
            - ./django/stocklooker:/stocklooker
        ports:
            - 8000:8000

    timescale:
        image: timescale/timescaledb:latest-pg12
        volumes:
            - ./timescale:/var/lib/postgresql/data
        ports:
            - 5500:5432
        environment:
            POSTGRES_PASSWORD: password1234

    grafana:
        image: grafana/grafana:7.5.8
        volumes:
            - ./grafana:/var/lib/grafana
        ports:
            - 3000:3000
        user: "472"