version: "3.9"

services:
    timescale:
        image: timescale/timescaledb:latest-pg12
        restart: always
        volumes:
            - ./timescale:/var/lib/postgresql/data
        ports:
           - "5500:5432"
        environment:
            POSTGRES_PASSWORD: password1234

        networks:
            - superset

    finhub-puller:
        image: finhub-puller:finhub-puller
        stop_grace_period: 60s
        restart: always
        networks:
            - superset

networks:
    superset:
        external:
            name: superset_default
