version: "3.9"

services:
    timescale:
        image: timescale/timescaledb:latest-pg12
        volumes:
            - ./timescale:/var/lib/postgresql/data
        ports:
            - "5500:5432"
        environment:
            POSTGRES_PASSWORD: password1234
        networks:
            - superset

networks:
    superset:
        external:
            name: superset_default
