# Generated by Django 3.2.3 on 2021-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Registration date')),
                ('ticker', models.CharField(help_text='Ticker for easy search the stock', max_length=10)),
                ('name', models.CharField(help_text='Name of the bussiness', max_length=50)),
                ('value', models.FloatField(help_text='Value of the stock this day')),
                ('low', models.FloatField(help_text='Low value on the day')),
                ('high', models.FloatField(help_text='High value on the day')),
                ('macd', models.FloatField(help_text='Macd value on that day')),
                ('signal', models.FloatField(help_text='Signal value on that day')),
                ('rsi', models.FloatField(help_text='Rsi value on that day')),
            ],
        ),
    ]
