# Generated by Django 3.2.3 on 2021-05-16 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='insert_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Registration date'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateTimeField(help_text='Data date'),
        ),
    ]
