# Generated by Django 3.2 on 2021-07-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('yahoo_ticker', models.CharField(help_text='Ticker for easy search the stock', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the bussiness', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.CharField(help_text='Id mix of date-ticker', max_length=50, primary_key=True, serialize=False)),
                ('insert_date', models.DateField(blank=True, help_text='Registration date')),
                ('stock_date', models.DateField(help_text='Data date')),
                ('yahoo_ticker', models.CharField(help_text='Ticker for easy search the stock', max_length=10)),
                ('open', models.FloatField(help_text='Value of the stock at the start of the day')),
                ('close', models.FloatField(help_text='Value of the stock at the end of the day')),
                ('low', models.FloatField(help_text='Low value on the day')),
                ('high', models.FloatField(help_text='High value on the day')),
                ('volume', models.BigIntegerField(help_text='Volume of transactions this day')),
                ('macd_12_26', models.FloatField(help_text='Macd value on that day')),
                ('signal_12_26', models.FloatField(help_text='Signal value on that day')),
                ('rsi_14', models.FloatField(help_text='Rsi value on that day')),
            ],
        ),
    ]
