# Generated by Django 3.2.3 on 2021-05-30 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Registration date')),
                ('date', models.DateTimeField(help_text='Data date')),
                ('yahoo_ticker', models.CharField(help_text='Ticker for easy search the stock', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Name of the bussiness', max_length=50)),
                ('market', models.CharField(blank=True, help_text='Name of the market, options for now: SP500, Nasdaq and Dow', max_length=50)),
                ('value', models.FloatField(help_text='Value of the stock this day')),
                ('low', models.FloatField(help_text='Low value on the day')),
                ('high', models.FloatField(help_text='High value on the day')),
                ('macd_12_26', models.FloatField(help_text='Macd value on that day')),
                ('signal_12_26', models.FloatField(help_text='Signal value on that day')),
                ('rsi_14', models.FloatField(help_text='Rsi value on that day')),
            ],
        ),
    ]
